name: Production release deployment

on:
  release:
    types: [published]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: '!github.event.release.prerelease'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT ID>:role/coa-github-actions-role
          role-session-name: ${{ github.run_id }}
          aws-region: eu-west-1
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env prod
